providers = ["python", "node"]

[phases.setup]
# Poprawne nazwy pakietów Nix:
# - python3 (alias na aktualną wersję)
# - nodejs-20_x (Node 20)
nixPkgs = ["python3", "nodejs-20_x"]

[start]
# jawnie ustawiamy start.sh jako komendę startową
cmd = "./start.sh"
