import express from "express";
import path from "path";
import { fileURLToPath } from "url";
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const app = express();
const PORT = process.env.PORT || 3000;
const STATIC_DIR = path.join(__dirname, "bowdowa");
app.use(express.static(STATIC_DIR));
app.get("*", (_, res) => res.sendFile(path.join(STATIC_DIR, "index.html")));
app.listen(PORT, "0.0.0.0", () => console.log("Serving", STATIC_DIR, "on", PORT));
